<package format="3">
  <name>tf2_rs</name>
  <version>0.1.0</version>
  <description>ROS 2 TF2 bindings for Rust using cxx</description>
  <maintainer email="33429185+olingo99@users.noreply.github.com">Theo Engels</maintainer>
  <license>MIT</license>

  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_msgs</depend>
  <depend>tf2_sensor_msgs</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>
